name: Pack validation (lax)
on:
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate pack (lax)
        uses: PopTracker/pack-checker-action@v1